# Generated by Django 4.0.3 on 2022-05-07 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storybooks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audio',
            name='shared_with',
            field=models.ManyToManyField(blank=True, to='storybooks.extended_user'),
        ),
        migrations.AlterField(
            model_name='interpretation',
            name='shared_editors',
            field=models.ManyToManyField(blank=True, related_name='interpretation_shared_editors', to='storybooks.extended_user'),
        ),
        migrations.AlterField(
            model_name='interpretation',
            name='shared_viewers',
            field=models.ManyToManyField(blank=True, related_name='interpretation_shared_viewers', to='storybooks.extended_user'),
        ),
        migrations.AlterField(
            model_name='interpretation_history',
            name='shared_editors',
            field=models.ManyToManyField(blank=True, related_name='interpretation_history_shared_editors', to='storybooks.extended_user'),
        ),
        migrations.AlterField(
            model_name='interpretation_history',
            name='shared_viewers',
            field=models.ManyToManyField(blank=True, related_name='interpretation_history_shared_viewers', to='storybooks.extended_user'),
        ),
    ]
