# Generated by Django 4.0.3 on 2022-04-08 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storybooks', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Interpretation',
            fields=[
                ('id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('public', models.BooleanField(default=False)),
                ('shared_editors', models.CharField(default='Not shared with any editors', max_length=2048)),
                ('shared_viewers', models.CharField(default='Not shared with any editors', max_length=2048)),
                ('audio_id', models.CharField(max_length=255)),
                ('title', models.CharField(max_length=255)),
                ('latest_text', models.CharField(max_length=255)),
                ('archived', models.BooleanField(default=False)),
                ('language_name', models.CharField(max_length=255)),
                ('spaced_by', models.CharField(max_length=255)),
                ('created_by', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_edited_at', models.DateTimeField(auto_now=True, null=True)),
                ('last_edited_by', models.CharField(max_length=255)),
                ('version', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'interepretation',
                'verbose_name_plural': 'interepretations',
            },
        ),
        migrations.CreateModel(
            name='Interpretation_History',
            fields=[
                ('id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('interpretation_id', models.CharField(max_length=255)),
                ('public', models.BooleanField(default=False)),
                ('shared_editors', models.CharField(default='Not shared with any editors', max_length=2048)),
                ('shared_viewers', models.CharField(default='Not shared with any editors', max_length=2048)),
                ('audio_id', models.CharField(max_length=255)),
                ('title', models.CharField(max_length=255)),
                ('latest_text', models.CharField(max_length=255)),
                ('archived', models.BooleanField(default=False)),
                ('language_name', models.CharField(max_length=255)),
                ('spaced_by', models.CharField(max_length=255)),
                ('created_by', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_edited_at', models.DateTimeField(auto_now=True, null=True)),
                ('last_edited_by', models.CharField(max_length=255)),
                ('version', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'interepretation history',
                'verbose_name_plural': 'interepretation history',
            },
        ),
        migrations.RenameField(
            model_name='audio',
            old_name='updated_at',
            new_name='last_updated_at',
        ),
        migrations.RenameField(
            model_name='audio',
            old_name='created_at',
            new_name='uploaded_at',
        ),
        migrations.RemoveField(
            model_name='audio',
            name='author',
        ),
        migrations.RemoveField(
            model_name='translation',
            name='audio',
        ),
        migrations.RemoveField(
            model_name='translation',
            name='author',
        ),
        migrations.AddField(
            model_name='audio',
            name='last_updated_by',
            field=models.CharField(default=0, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='audio',
            name='public',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='audio',
            name='shared_with',
            field=models.CharField(default='Not shared with anyone', max_length=2048),
        ),
        migrations.AddField(
            model_name='audio',
            name='uploaded_by',
            field=models.CharField(default='Justin', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='translation',
            name='audio_id',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='translation',
            name='author_id',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='audio',
            name='id',
            field=models.CharField(max_length=255, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='story',
            name='translation',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='translation',
            name='last_updated_by',
            field=models.CharField(default='Justin', max_length=255),
            preserve_default=False,
        ),
    ]
