# Generated by Django 3.2.9 on 2021-11-03 18:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('storybooks', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='audio',
            old_name='createdAt',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='audio',
            old_name='updatedAt',
            new_name='updated_at',
        ),
        migrations.RenameField(
            model_name='translation',
            old_name='createdAt',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='translation',
            old_name='updatedAt',
            new_name='updated_at',
        ),
        migrations.RemoveField(
            model_name='audio',
            name='lastUpdatedBy',
        ),
        migrations.RemoveField(
            model_name='translation',
            name='lastUpdatedBy',
        ),
        migrations.AddField(
            model_name='audio',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audio_author', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='translation',
            name='last_updated_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='last_updated_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='translation',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='translation_author', to=settings.AUTH_USER_MODEL),
        ),
    ]
