# Generated by Django 4.0.5 on 2022-11-12 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storybooks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='audio',
            name='peaks',
            field=models.TextField(blank=True, null=True),
        ),
    ]
