# Generated by Django 4.0.5 on 2023-01-15 20:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('storybooks', '0002_audio_peaks'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='story',
            name='translation',
        ),
        migrations.RemoveField(
            model_name='translation',
            name='language',
        ),
        migrations.DeleteModel(
            name='Language',
        ),
        migrations.DeleteModel(
            name='Story',
        ),
        migrations.DeleteModel(
            name='Translation',
        ),
    ]
