# Generated by Django 3.2.9 on 2021-11-10 00:04

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('storybooks', '0002_auto_20211103_1824'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='story',
            name='translation',
        ),
        migrations.AddField(
            model_name='story',
            name='index',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='story',
            name='timestamp',
            field=models.DateTimeField(default=datetime.date(2021, 11, 9)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='story',
            name='word',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('next_page', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='next', to='storybooks.page')),
                ('previous_page', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='previous', to='storybooks.page')),
                ('translation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='storybooks.translation')),
            ],
            options={
                'verbose_name': 'page',
                'verbose_name_plural': 'pages',
            },
        ),
        migrations.AddField(
            model_name='story',
            name='page',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='storybooks.page'),
        ),
    ]
