# Generated by Django 4.0.3 on 2022-04-19 04:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('storybooks', '0002_interpretation_interpretation_history_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Interpretation',
        ),
        migrations.DeleteModel(
            name='Interpretation_History',
        ),
        migrations.AlterField(
            model_name='audio',
            name='last_updated_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audio_last_updated_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.RemoveField(
            model_name='audio',
            name='shared_with',
        ),
        migrations.AddField(
            model_name='audio',
            name='shared_with',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='audio',
            name='uploaded_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audio_uploaded_by', to=settings.AUTH_USER_MODEL),
        ),
    ]
