# Generated by Django 4.0.5 on 2023-06-20 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storybooks', '0003_remove_story_translation_remove_translation_language_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Language',
            fields=[
                ('name', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('bAdjust', models.CharField(default='Adjust', max_length=255)),
                ('bClose', models.CharField(default='Close', max_length=255)),
                ('bInterpretation', models.CharField(default='Interpretation', max_length=255)),
                ('bViewing', models.CharField(default='Viewing', max_length=255)),
                ('bDownload', models.CharField(default='Download', max_length=255)),
                ('bScribing', models.CharField(default='Scribing', max_length=255)),
                ('bEditing', models.CharField(default='Editing', max_length=255)),
                ('bRefining', models.CharField(default='Refining', max_length=255)),
                ('bStudying', models.CharField(default='Studying', max_length=255)),
                ('bResetSensitivity', models.CharField(default='Reset Sensitivity', max_length=255)),
                ('bNewPrompt', models.CharField(default='New Prompt', max_length=255)),
                ('bClearNew', models.CharField(default='Clear New', max_length=255)),
                ('bNewPhrase', models.CharField(default='New Phrase', max_length=255)),
                ('sPlaybackSpeed', models.CharField(default='playback speed', max_length=255)),
                ('sZoom', models.CharField(default='zoom', max_length=255)),
                ('sChangeFontSize', models.CharField(default='change font size', max_length=255)),
                ('sScribeLessMore', models.CharField(default='scribe less / more', max_length=255)),
                ('sHighlightLessMore', models.CharField(default='highlight less / more', max_length=255)),
                ('sPhraseLength', models.CharField(default='phrase length', max_length=255)),
                ('cClearSelection', models.CharField(default='Clear Selection', max_length=255)),
                ('cRepeatOnOff', models.CharField(default='Repeat On / Off', max_length=255)),
                ('cAutoscrollOnOff', models.CharField(default='Autoscroll On / Off', max_length=255)),
                ('oCreateNewInterpretation', models.CharField(default='Create New Interpretation', max_length=255)),
                ('oUploadInterpretationFile', models.CharField(default='Upload Inter-pretation File', max_length=255)),
                ('oAddAnotherConsole', models.CharField(default='Add Another Console', max_length=255)),
            ],
        ),
    ]
