# Generated by Django 4.0.3 on 2022-04-19 04:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storybooks', '0003_delete_interpretation_delete_interpretation_history_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audio',
            name='last_updated_by',
            field=models.CharField(max_length=255),
        ),
        migrations.RemoveField(
            model_name='audio',
            name='shared_with',
        ),
        migrations.AddField(
            model_name='audio',
            name='shared_with',
            field=models.CharField(default='Not shared with anyone', max_length=2048),
        ),
        migrations.AlterField(
            model_name='audio',
            name='uploaded_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 4, 19, 4, 27, 39, 560860)),
        ),
        migrations.AlterField(
            model_name='audio',
            name='uploaded_by',
            field=models.CharField(max_length=255),
        ),
    ]
