# Generated by Django 4.0.3 on 2022-04-19 04:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storybooks', '0004_alter_audio_last_updated_by_remove_audio_shared_with_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audio',
            name='uploaded_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 4, 19, 4, 28, 15, 911382)),
        ),
    ]
