# Generated by Django 4.0.5 on 2023-06-20 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storybooks', '0004_language'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='language',
            name='cAutoscrollOnOff',
        ),
        migrations.RemoveField(
            model_name='language',
            name='cRepeatOnOff',
        ),
        migrations.AddField(
            model_name='language',
            name='cAutoscroll',
            field=models.CharField(default='Autoscroll', max_length=255),
        ),
        migrations.AddField(
            model_name='language',
            name='cRepeat',
            field=models.CharField(default='Repeat', max_length=255),
        ),
    ]
