# Generated by Django 4.0.5 on 2023-06-21 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storybooks', '0006_language_ngetlatestappversion_language_ngetpagelink_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='language',
            name='bSave',
            field=models.CharField(default='Save', max_length=255),
        ),
    ]
