# Generated by Django 4.0.3 on 2022-04-26 04:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('storybooks', '0006_alter_audio_uploaded_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='Extended_User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_ID', models.CharField(max_length=255)),
                ('display_name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('anonymous', models.BooleanField(default=False)),
            ],
        ),
        migrations.RemoveField(
            model_name='audio',
            name='shared_with',
        ),
        migrations.AlterField(
            model_name='audio',
            name='uploaded_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='story',
            name='translation',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='storybooks.translation'),
        ),
        migrations.CreateModel(
            name='Interpretation_History',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('public', models.BooleanField(default=False)),
                ('title', models.CharField(max_length=255)),
                ('latest_text', models.TextField()),
                ('archived', models.BooleanField(default=False)),
                ('spaced_by', models.CharField(default='', max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_edited_at', models.DateTimeField(auto_now=True)),
                ('version', models.IntegerField(default=1)),
                ('audio_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interpretation_history_audio_ID', to='storybooks.audio')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interpretation_history_created_by', to='storybooks.extended_user')),
                ('language_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interpretation_history_language_name', to='storybooks.language')),
                ('last_edited_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interpretation_history_last_edited_by', to='storybooks.extended_user')),
                ('shared_editors', models.ManyToManyField(related_name='interpretation_history_shared_editors', to='storybooks.extended_user')),
                ('shared_viewers', models.ManyToManyField(related_name='interpretation_history_shared_viewers', to='storybooks.extended_user')),
            ],
            options={
                'verbose_name': 'interpretation history',
                'verbose_name_plural': 'interpretation history',
            },
        ),
        migrations.CreateModel(
            name='Interpretation',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('public', models.BooleanField(default=False)),
                ('title', models.CharField(max_length=255)),
                ('latest_text', models.TextField()),
                ('archived', models.BooleanField(default=False)),
                ('spaced_by', models.CharField(default='', max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_edited_at', models.DateTimeField(auto_now=True)),
                ('version', models.IntegerField(default=1)),
                ('audio_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interpretation_audio_ID', to='storybooks.audio')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interpretation_created_by', to='storybooks.extended_user')),
                ('language_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interpretation_language_name', to='storybooks.language')),
                ('last_edited_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interpretation_last_edited_by', to='storybooks.extended_user')),
                ('shared_editors', models.ManyToManyField(related_name='interpretation_shared_editors', to='storybooks.extended_user')),
                ('shared_viewers', models.ManyToManyField(related_name='interpretation_shared_viewers', to='storybooks.extended_user')),
            ],
            options={
                'verbose_name': 'interpretation',
                'verbose_name_plural': 'interpretations',
            },
        ),
        migrations.CreateModel(
            name='Content',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value_index', models.IntegerField()),
                ('value', models.CharField(max_length=255)),
                ('audio_time', models.TimeField(default=None)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateTimeField(default=None)),
                ('audio_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='content_audio_id', to='storybooks.audio')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='content_created_by', to='storybooks.extended_user')),
                ('interpretation_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='storybooks.interpretation')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='content_updated_by', to='storybooks.extended_user')),
            ],
            options={
                'verbose_name': 'content',
                'verbose_name_plural': 'contents',
            },
        ),
        migrations.AddField(
            model_name='audio',
            name='shared_with',
            field=models.ManyToManyField(to='storybooks.extended_user'),
        ),
        migrations.AlterField(
            model_name='audio',
            name='uploaded_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audio_uploaded_by', to='storybooks.extended_user'),
        ),
    ]
