# Generated by Django 4.0.5 on 2023-06-21 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storybooks', '0007_language_bsave'),
    ]

    operations = [
        migrations.AddField(
            model_name='language',
            name='code',
            field=models.CharField(default='en', max_length=255),
        ),
    ]
